### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by patternseek** [puli/issues#68]
On a freshly cloned copy of master for puli/manager, after installing phpunit and adding sebastian/comparator which seems to be required to run the test suite (probably should be a dev dependency?) I get the following failures:

```
There were 3 failures:

1) Puli\Manager\Tests\Config\ConfigJsonReaderTest::testReadConfigFileFailsIfDecodingNotPossible
Failed asserting that exception of type "Puli\Manager\Api\Config\NoSuchConfigKeyException" matches expected exception "\Puli\Manager\Api\InvalidConfigException". Message was: "The config key "plugins" does not exist." at
#0 /home/tolan/ttmp/pulitest/manager/src/Api/Config/Config.php(333): Puli\Manager\Api\Config\NoSuchConfigKeyException::forKey('plugins')
#1 /home/tolan/ttmp/pulitest/manager/src/Config/ConfigJsonReader.php(46): Puli\Manager\Api\Config\Config->set('plugins', Array)
#2 /home/tolan/ttmp/pulitest/manager/tests/Config/ConfigJsonReaderTest.php(101): Puli\Manager\Config\ConfigJsonReader->readConfigFile('/home/tolan/ttm...')
#3 [internal function]: Puli\Manager\Tests\Config\ConfigJsonReaderTest->testReadConfigFileFailsIfDecodingNotPossible()
#4 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestCase.php(866): ReflectionMethod->invokeArgs(Object(Puli\Manager\Tests\Config\ConfigJsonReaderTest), Array)
#5 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestCase.php(743): PHPUnit_Framework_TestCase->runTest()
#6 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestResult.php(610): PHPUnit_Framework_TestCase->runBare()
#7 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestCase.php(699): PHPUnit_Framework_TestResult->run(Object(Puli\Manager\Tests\Config\ConfigJsonReaderTest))
#8 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestSuite.php(731): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#9 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestSuite.php(731): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#10 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(424): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#11 /usr/share/php/PHPUnit/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#12 /usr/share/php/PHPUnit/TextUI/Command.php(138): PHPUnit_TextUI_Command->run(Array, true)
#13 /usr/bin/phpunit(42): PHPUnit_TextUI_Command::main()
#14 {main}.

/usr/share/php/PHPUnit/TextUI/Command.php:186
/usr/share/php/PHPUnit/TextUI/Command.php:138

2) Puli\Manager\Tests\Package\PackageJsonReaderTest::testReadPackageFileFailsIfDecodingNotPossible
Failed asserting that exception of type "\Puli\Manager\Api\InvalidConfigException" is thrown.

/usr/share/php/PHPUnit/TextUI/Command.php:186
/usr/share/php/PHPUnit/TextUI/Command.php:138

3) Puli\Manager\Tests\Package\PackageJsonReaderTest::testReadRootPackageFileFailsIfDecodingNotPossible
Failed asserting that exception of type "\Puli\Manager\Api\InvalidConfigException" is thrown.

/usr/share/php/PHPUnit/TextUI/Command.php:186
/usr/share/php/PHPUnit/TextUI/Command.php:138
```

PHP 5.6.5-1 on Debian unstable/testing.

**Comment by webmozart** [comment]
Hm, I cannot reproduce this. I added PHPUnit as dev dependency in puli/manager@5f3c5a76e3b2e2279641727890ee8309043be9fe.

If this still fails for you, can you checkout https://github.com/webmozart/json and run its test suite on your computer? Maybe that gives a clue.

**Comment by patternseek** [comment]
I'm still getting the errors on master yes. The JSON package is also failing, here's the output:
```
 tolan@orbit ⮀ ~/t/pulitest ⮀
 ❯ git clone https://github.com/webmozart/json.git                                                                                                                                                                                  [11:24:14]
Cloning into 'json'...
remote: Counting objects: 218, done.
remote: Total 218 (delta 0), reused 0 (delta 0), pack-reused 218
Receiving objects: 100% (218/218), 44.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (138/138), done.
Checking connectivity... done.

 tolan@orbit ⮀ ~/t/pulitest ⮀
 ❯ cd json                                                                                                                                                                                                                          [11:24:19]

 tolan@orbit ⮀ ~/t/p/json ⮀ ⭠ master ⮀
 ❯ ~/storage/workspace/agile/bin/composer.phar install                                                                                                                                                                              [11:24:38]
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing justinrainbow/json-schema (1.4.1)
    Loading from cache

  - Installing seld/jsonlint (1.3.1)
    Loading from cache

Writing lock file
Generating autoload files

 tolan@orbit ⮀ ~/t/p/json ⮀ ⭠ master ⮀
 ❯ phpunit                                                                                                                                                                                                                          [11:24:43]
PHPUnit 4.2.6 by Sebastian Bergmann.

Configuration read from /home/tolan/ttmp/pulitest/json/phpunit.xml.dist

........F.....................F.................................. 65 / 86 ( 75%)
.....................

Time: 83 ms, Memory: 6.00Mb

There were 2 failures:

1) Webmozart\Json\Tests\JsonDecoderTest::testDecodeFailsIfNotUtf8
Failed asserting that exception of type "\Webmozart\Json\DecodingFailedException" is thrown.

2) Webmozart\Json\Tests\JsonDecoderTest::testDecodeFileFailsIfNotUtf8
Failed asserting that exception of type "\Webmozart\Json\DecodingFailedException" is thrown.
                                        
FAILURES!                               
Tests: 86, Assertions: 112, Failures: 2.
```

**Comment by webmozart** [comment]
Can you debug the values of `$decoded`, `$options` and `$json` in `JsonDecoder::decodeJson()` in those tests?

**Comment by webmozart** [comment]
Any news?

**Comment by patternseek** [comment]
Sorry, super busy at the moment. Will come back to this as soon as possible.

Bernhard Schussek wrote:

**Comment by stof** [comment]
@patternseek You are running tests with PHPUnit 4.2. you should use the version installed through composer instead to have the right version. the testsuite relies on PHPUnit 4.6

**Comment by patternseek** [comment]
@stof OK. Using the phpunit installed by composer for manager master, which is 4.8-g159ab0c, it still fails I'm afraid:

```
 tolan@orbit ⮀ ~/t/p/manager ⮀ ⭠ master ⮀
 ❯ ./vendor/bin/phpunit                                                                                                                                                                                                             [18:57:09]
PHPUnit 4.8-g159ab0c by Sebastian Bergmann and contributors.

.............................................................   61 / 1380 (  4%)
.............................................................  122 / 1380 (  8%)
.............................................................  183 / 1380 ( 13%)
.............................................................  244 / 1380 ( 17%)
.............................................................  305 / 1380 ( 22%)
.............................................................  366 / 1380 ( 26%)
.............................................................  427 / 1380 ( 30%)
.............................................................  488 / 1380 ( 35%)
.............................................................  549 / 1380 ( 39%)
.............................................................  610 / 1380 ( 44%)
.............................................................  671 / 1380 ( 48%)
....................................F........................  732 / 1380 ( 53%)
.............................................................  793 / 1380 ( 57%)
.............................................................  854 / 1380 ( 61%)
.................................................SSSSSSSSSSSS  915 / 1380 ( 66%)
.............................................................  976 / 1380 ( 70%)
...............................................FF............ 1037 / 1380 ( 75%)
............................................................. 1098 / 1380 ( 79%)
............................................................. 1159 / 1380 ( 83%)
............................................................. 1220 / 1380 ( 88%)
............................................................. 1281 / 1380 ( 92%)
............................................................. 1342 / 1380 ( 97%)
......................................

Time: 12.56 seconds, Memory: 36.50Mb

There were 3 failures:

1) Puli\Manager\Tests\Config\ConfigJsonReaderTest::testReadConfigFileFailsIfDecodingNotPossible
Failed asserting that exception of type "Puli\Manager\Api\Config\NoSuchConfigKeyException" matches expected exception "\Puli\Manager\Api\InvalidConfigException". Message was: "The config key "plugins" does not exist." at
#0 /home/tolan/ttmp/pulitest/manager/src/Api/Config/Config.php(333): Puli\Manager\Api\Config\NoSuchConfigKeyException::forKey('plugins')
#1 /home/tolan/ttmp/pulitest/manager/src/Config/ConfigJsonReader.php(46): Puli\Manager\Api\Config\Config->set('plugins', Array)
#2 /home/tolan/ttmp/pulitest/manager/tests/Config/ConfigJsonReaderTest.php(101): Puli\Manager\Config\ConfigJsonReader->readConfigFile('/home/tolan/ttm...')
#3 [internal function]: Puli\Manager\Tests\Config\ConfigJsonReaderTest->testReadConfigFileFailsIfDecodingNotPossible()
#4 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestCase.php(866): ReflectionMethod->invokeArgs(Object(Puli\Manager\Tests\Config\ConfigJsonReaderTest), Array)
#5 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestCase.php(743): PHPUnit_Framework_TestCase->runTest()
#6 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestResult.php(610): PHPUnit_Framework_TestCase->runBare()
#7 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestCase.php(699): PHPUnit_Framework_TestResult->run(Object(Puli\Manager\Tests\Config\ConfigJsonReaderTest))
#8 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestSuite.php(731): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#9 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/Framework/TestSuite.php(731): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#10 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(438): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#11 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/TextUI/Command.php(154): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#12 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/src/TextUI/Command.php(106): PHPUnit_TextUI_Command->run(Array, true)
#13 /home/tolan/ttmp/pulitest/manager/vendor/phpunit/phpunit/phpunit(36): PHPUnit_TextUI_Command::main()
#14 {main}.

2) Puli\Manager\Tests\Package\PackageJsonReaderTest::testReadPackageFileFailsIfDecodingNotPossible
Failed asserting that exception of type "\Puli\Manager\Api\InvalidConfigException" is thrown.

3) Puli\Manager\Tests\Package\PackageJsonReaderTest::testReadRootPackageFileFailsIfDecodingNotPossible
Failed asserting that exception of type "\Puli\Manager\Api\InvalidConfigException" is thrown.

FAILURES!
Tests: 1380, Assertions: 2995, Failures: 3, Skipped: 12.
>>> elapsed time 13s                                                                                                                                                                                                                           
```

@webmozart 
```
testDecodeFailsIfNotUtf8():
var_export([$json, $decoded, $options], true)
array (
  0 => '{
    "name": "my/�pplication"
}
',
  1 => 
  stdClass::__set_state(array(
     'name' => 'my/�pplication',
  )),
  2 => 0,
)

testDecodeFileFailsIfNotUtf8():
var_export([$json, $decoded, $options], true)
array (
  0 => '{
    "name": "my/�pplication"
}
',
  1 => 
  stdClass::__set_state(array(
     'name' => 'my/�pplication',
  )),
  2 => 0,
)
```

**Comment by stof** [comment]
Can you should the output of ``php -i |grep json`` ?

**Comment by patternseek** [comment]
```sh
❯ php -i | grep json                                                                                                                                                                                                               [15:03:25]
/etc/php5/cli/conf.d/20-json.ini,
json
json support => enabled
json version => 1.3.6
json support => no
```

That final line is from the memcached extension.

**Comment by patternseek** [comment]
It seems that the fundamental problem is that decoding of that string /is/ possible on my install as json_decode() returns a stdObject with the apparently illegal string untouched, so testReadPackageFileFailsIfDecodingNotPossible() and testDecodeFailsIfNotUtf8() will fail.

I notice the test is skipped for Ubuntu. I'm on Debian so there's a good chance it's using the same PHP packages as Ubuntu. I see that Redhat and Debian have dumped the mainline json extension in favour of json-c here : https://github.com/remicollet/pecl-json-c . I've checked and that's what I have installed for the php5-json .deb. AFAICT this is being used by newer Redhat releases too so a more generic test for the alternate extension may be needed.

https://github.com/remicollet/pecl-json-c/issues/9

**Comment by patternseek** [comment]
The only way I can see to check for that extension is it's mentioned in the output of php -i / phpinfo() in the modules section:
JSON-C headers version => 0.11.99
JSON-C library version => 0.11.99

Not sure if there's a neater way to get that information or not.

**Comment by stof** [comment]
@webmozart the JSONC extension indeed does not validate UTF-8 encoding whne parsing, because the underlying library does not (see https://github.com/json-c/json-c/issues/122 and https://github.com/remicollet/pecl-json-c/issues/9).
Rather than detecting Ubuntu PHP builds, I suggest detecting the usage of the JSONC extension. the feature detection can be done through ``defined('JSON_C_VERSION')``

**Comment by stof** [comment]
See https://github.com/webmozart/json/pull/3 for the first part

**Comment by webmozart** [comment]
Thanks the both of you!

@patternseek Can you check whether @stof's change in webmozart/json#3 fixes this issue for you?

**Comment by stof** [comment]
@webmozart I sent another PR fixing the puli/manager testsuite, which is the one needed by @patternseek (he would have got the same kind of issues when running the webmozart/json tests, but this is not what is reported here)

note that I can confirm this issue myself. I'm using ondrej's ppa for Ubuntu. So I still use JSONC for the JSON extension, but my PHP version does not have ubuntu in its name. I was getting the same issues when running tests.

**Comment by webmozart** [comment]
Perfect, thanks @stof!

**Comment by patternseek** [comment]
Yes webmozart/json#3 fixes the tests for me.
